"use client";
import dynamic from 'next/dynamic';
import {useEffect,useMemo,useState} from 'react';
import {Brain,GitBranch,Search,Download,Plus,Target,AlertTriangle,CheckCircle2} from 'lucide-react';
const Graph=dynamic(()=>import('react-force-graph-2d'),{ssr:false});
type Kind='company'|'decision'|'memory'|'risk'|'task'|'pattern'|'goal';
type Node={id:string;kind:Kind;title:string;body:string;created:string};
type Link={source:string;target:string;type:string};
type Store={nodes:Node[];links:Link[];feedback:{id:string;useful:boolean}[]};
const seed:Store={nodes:[
{id:'pivot',kind:'company',title:'Pivot AI',body:'AI receptionist and missed-call recovery SaaS.',created:new Date().toISOString()},
{id:'sitebrief',kind:'company',title:'SiteBrief AI',body:'Natural-language AI website generation platform.',created:new Date().toISOString()},
{id:'logistics',kind:'company',title:'AL Logistics LLC',body:'Trucking and logistics company.',created:new Date().toISOString()},
{id:'goal',kind:'goal',title:'Build ownership and recurring revenue',body:'Prioritize scalable, automated businesses that increase freedom and family stability.',created:new Date().toISOString()},
{id:'pattern',kind:'pattern',title:'Too many active ideas compete for execution time',body:'Hypothesis requiring confirmation through outcomes.',created:new Date().toISOString()},
{id:'risk',kind:'risk',title:'Project switching slows completion',body:'Focus may be divided across too many builds.',created:new Date().toISOString()}],links:[{source:'pivot',target:'goal',type:'supports'},{source:'sitebrief',target:'goal',type:'supports'},{source:'logistics',target:'goal',type:'supports'},{source:'pattern',target:'risk',type:'causes'}],feedback:[]};
function classify(text:string):Kind{const s=text.toLowerCase();if(/decid|choose|pause|stop|start/.test(s))return'decision';if(/risk|danger|concern|blocked|fail/.test(s))return'risk';if(/need to|must|task|next step|remind/.test(s))return'task';if(/pattern|again|keeps happening|recurring/.test(s))return'pattern';if(/goal|target|aim/.test(s))return'goal';return'memory'}
export default function Home(){const[store,setStore]=useState<Store>(seed);const[text,setText]=useState('');const[q,setQ]=useState('');const[tab,setTab]=useState<'home'|'graph'>('home');const[selected,setSelected]=useState<Node|null>(null);useEffect(()=>{const x=localStorage.getItem('alos-v1');if(x)try{setStore(JSON.parse(x))}catch{}},[]);useEffect(()=>{localStorage.setItem('alos-v1',JSON.stringify(store))},[store]);
const visible=useMemo(()=>store.nodes.filter(n=>`${n.title} ${n.body} ${n.kind}`.toLowerCase().includes(q.toLowerCase())),[store.nodes,q]);const data=useMemo(()=>({nodes:visible.map(n=>({...n,name:n.title})),links:store.links.filter(l=>visible.some(n=>n.id===l.source)&&visible.some(n=>n.id===l.target))}),[visible,store.links]);
function add(){const body=text.trim();if(!body)return;const kind=classify(body);const id=`${kind}-${Date.now()}`;const n:Node={id,kind,title:body.length>72?body.slice(0,69)+'...':body,body,created:new Date().toISOString()};const refs=store.nodes.filter(x=>x.kind==='company'&&body.toLowerCase().includes(x.title.toLowerCase().replace(' llc','')));setStore(s=>({...s,nodes:[n,...s.nodes],links:[...refs.map(r=>({source:id,target:r.id,type:'belongs_to'})),...s.links]}));setText('')}
const action=store.nodes.find(n=>n.kind==='task')?.title||store.nodes.find(n=>n.kind==='risk')?.title||'Capture the single highest-value blocker affecting revenue today.';
function backup(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(store,null,2)],{type:'application/json'}));a.download='alos-backup.json';a.click()}
return <main><aside><div className="brand"><Brain/> <b>ALOS</b><span>Second Mind</span></div><button onClick={()=>setTab('home')} className={tab==='home'?'active':''}><Target/>Command</button><button onClick={()=>setTab('graph')} className={tab==='graph'?'active':''}><GitBranch/>Graph</button><button onClick={backup}><Download/>Backup</button></aside><section className="work"><header><div><small>Gagandeep's cognitive operating system</small><h1>{tab==='home'?'Command Center':'Knowledge Graph'}</h1></div><label><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search your second mind"/></label></header><div className="capture"><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Write naturally: decision, blocker, task, lesson, pattern, risk, idea..."/><button onClick={add}><Plus/>Save</button></div>{tab==='home'?<><div className="roi"><span>Highest-ROI next action</span><h2>{action}</h2><p>Derived from your open tasks and risks.</p></div><div className="stats"><article><b>{store.nodes.length}</b><span>Knowledge nodes</span></article><article><b>{store.links.length}</b><span>Connections</span></article><article><b>{store.feedback.length}</b><span>Feedback signals</span></article></div><div className="grid">{visible.map(n=><article key={n.id} className="card" onClick={()=>setSelected(n)}><div className="type"><i className={n.kind}/>{n.kind}</div><h3>{n.title}</h3><p>{n.body}</p></article>)}</div></>:<div className="graph"><Graph graphData={data} nodeAutoColorBy="kind" nodeLabel="title" linkLabel={(l:any)=>l.type} linkDirectionalArrowLength={3} onNodeClick={(n:any)=>setSelected(n)}/></div>}</section>{selected&&<div className="shade" onClick={()=>setSelected(null)}><div className="drawer" onClick={e=>e.stopPropagation()}><button className="x" onClick={()=>setSelected(null)}>×</button><span className="pill">{selected.kind}</span><h2>{selected.title}</h2><p>{selected.body}</p><hr/><h3>Was this useful?</h3><div className="feedback"><button onClick={()=>setStore(s=>({...s,feedback:[...s.feedback.filter(f=>f.id!==selected.id),{id:selected.id,useful:true}]}))}><CheckCircle2/>Useful</button><button onClick={()=>setStore(s=>({...s,feedback:[...s.feedback.filter(f=>f.id!==selected.id),{id:selected.id,useful:false}]}))}><AlertTriangle/>Not useful</button></div></div></div>}</main>}